FROM node:lts

WORKDIR /app
COPY health.sh .
RUN chmod +x health.sh
RUN  mkdir /invoices/
COPY resources/ /invoices/

COPY package*.json .
RUN npm ci --include=dev

COPY . .
RUN ./node_modules/.bin/tsc --build

EXPOSE 3000

CMD ["node", "dist/src/index.js"]